language: go

go:
  - "1.10"
  - "1.11"
  - "tip"

notifications:
  on_success: false
  on_failure: always

env:
  global:
    - PATH=$GOPATH/bin:$PATH

before_install:
  # Move git repo cloned by Travis-CI as then we get the correct branch
  # automatically.
  - mkdir -p ${GOPATH}/src/zikichombo.org
  - cd ..
  - mv sound ${GOPATH}/src/zikichombo.org/
  - cd ${GOPATH}/src/zikichombo.org/sound

install:
  - go get -t ./...

before_script:
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u golang.org/x/tools/cmd/goimports
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/mattn/goveralls
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
  # TODO: Move mewmew/ci to zc/meta?
  - wget https://raw.githubusercontent.com/mewmew/ci/master/ci_checks.sh
  - chmod +x ci_checks.sh

script:
  - ./ci_checks.sh
